version: '3'
services:
  app:
    image: ishwarik7/docker-web-app
    restart: always
    ports:
      - "3001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3